production:
  adapter: mysql2
  encoding: utf8mb4
  database: pim
  pool: 5
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>
  #host: mariadb.filmer.net
  #socket: /tmp/mysql.sock
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  encoding: utf8mb4
  database: pim
  pool: 5
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

